; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -p loop-vectorize -force-vector-width=16 -force-vector-interleave=1 -S %s | FileCheck %s

target datalayout = "e-m:o-i64:64-i128:128-n32:64-S128"

; umin/umax reductions over zero-extended i8 values with i8 start values should
; be performed on i8 lanes.
define void @umin_umax_i8(ptr %p, i64 %n, ptr %out) {
; CHECK-LABEL: define void @umin_umax_i8(
; CHECK:       vector.body:
; CHECK:         [[VEC_PHI:%.*]] = phi <16 x i8> [ splat (i8 -1), %vector.ph ], [ [[TMP2:%.*]], %vector.body ]
; CHECK:         [[VEC_PHI1:%.*]] = phi <16 x i8> [ zeroinitializer, %vector.ph ], [ [[TMP3:%.*]], %vector.body ]
; CHECK:         [[WIDE_LOAD:%.*]] = load <16 x i8>, ptr {{.*}}, align 1
; CHECK:         [[TMP2]] = call <16 x i8> @llvm.umin.v16i8(<16 x i8> [[VEC_PHI]], <16 x i8> [[WIDE_LOAD]])
; CHECK:         [[TMP3]] = call <16 x i8> @llvm.umax.v16i8(<16 x i8> [[VEC_PHI1]], <16 x i8> [[WIDE_LOAD]])
; CHECK:       middle.block:
; CHECK:         [[TMP5:%.*]] = call i8 @llvm.vector.reduce.umin.v16i8(<16 x i8> [[TMP2]])
; CHECK:         zext i8 [[TMP5]] to i32
; CHECK:         [[TMP7:%.*]] = call i8 @llvm.vector.reduce.umax.v16i8(<16 x i8> [[TMP3]])
; CHECK:         zext i8 [[TMP7]] to i32
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %lo = phi i32 [ 255, %entry ], [ %lo.next, %loop ]
  %hi = phi i32 [ 0, %entry ], [ %hi.next, %loop ]
  %gep = getelementptr inbounds i8, ptr %p, i64 %iv
  %v = load i8, ptr %gep, align 1
  %c = zext i8 %v to i32
  %lo.next = call i32 @llvm.umin.i32(i32 %lo, i32 %c)
  %hi.next = call i32 @llvm.umax.i32(i32 %hi, i32 %c)
  %iv.next = add nuw nsw i64 %iv, 1
  %ec = icmp eq i64 %iv.next, %n
  br i1 %ec, label %exit, label %loop

exit:
  %lo.lcssa = phi i32 [ %lo.next, %loop ]
  %hi.lcssa = phi i32 [ %hi.next, %loop ]
  %shl = shl i32 %hi.lcssa, 16
  %res = add i32 %shl, %lo.lcssa
  store i32 %res, ptr %out, align 4
  ret void
}

; The start value of the umin reduction does not fit into i8, so the reduction
; is only narrowed to i16.
define void @umin_start_too_wide(ptr %p, i64 %n, ptr %out) {
; CHECK-LABEL: define void @umin_start_too_wide(
; CHECK:         call <16 x i16> @llvm.umin.v16i16(
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %lo = phi i32 [ 256, %entry ], [ %lo.next, %loop ]
  %gep = getelementptr inbounds i8, ptr %p, i64 %iv
  %v = load i8, ptr %gep, align 1
  %c = zext i8 %v to i32
  %lo.next = call i32 @llvm.umin.i32(i32 %lo, i32 %c)
  %iv.next = add nuw nsw i64 %iv, 1
  %ec = icmp eq i64 %iv.next, %n
  br i1 %ec, label %exit, label %loop

exit:
  %lo.lcssa = phi i32 [ %lo.next, %loop ]
  store i32 %lo.lcssa, ptr %out, align 4
  ret void
}

; smin/smax reductions over sign-extended i8 values are narrowed as well.
define void @smin_smax_i8(ptr %p, i64 %n, ptr %out) {
; CHECK-LABEL: define void @smin_smax_i8(
; CHECK:         call <16 x i8> @llvm.smin.v16i8(
; CHECK:         call <16 x i8> @llvm.smax.v16i8(
; CHECK:         [[R0:%.*]] = call i8 @llvm.vector.reduce.smin.v16i8(
; CHECK:         sext i8 [[R0]] to i32
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %lo = phi i32 [ 127, %entry ], [ %lo.next, %loop ]
  %hi = phi i32 [ -128, %entry ], [ %hi.next, %loop ]
  %gep = getelementptr inbounds i8, ptr %p, i64 %iv
  %v = load i8, ptr %gep, align 1
  %c = sext i8 %v to i32
  %lo.next = call i32 @llvm.smin.i32(i32 %lo, i32 %c)
  %hi.next = call i32 @llvm.smax.i32(i32 %hi, i32 %c)
  %iv.next = add nuw nsw i64 %iv, 1
  %ec = icmp eq i64 %iv.next, %n
  br i1 %ec, label %exit, label %loop

exit:
  %lo.lcssa = phi i32 [ %lo.next, %loop ]
  %hi.lcssa = phi i32 [ %hi.next, %loop ]
  %res = add i32 %lo.lcssa, %hi.lcssa
  store i32 %res, ptr %out, align 4
  ret void
}

; A zext from i16 keeps the reduction at i16.
define void @umax_i16(ptr %p, i64 %n, ptr %out) {
; CHECK-LABEL: define void @umax_i16(
; CHECK:         call <16 x i16> @llvm.umax.v16i16(
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %hi = phi i32 [ 0, %entry ], [ %hi.next, %loop ]
  %gep = getelementptr inbounds i16, ptr %p, i64 %iv
  %v = load i16, ptr %gep, align 2
  %c = zext i16 %v to i32
  %hi.next = call i32 @llvm.umax.i32(i32 %hi, i32 %c)
  %iv.next = add nuw nsw i64 %iv, 1
  %ec = icmp eq i64 %iv.next, %n
  br i1 %ec, label %exit, label %loop

exit:
  %hi.lcssa = phi i32 [ %hi.next, %loop ]
  store i32 %hi.lcssa, ptr %out, align 4
  ret void
}
