; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -passes=licm < %s | FileCheck %s

target datalayout = "e-m:o-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-n32:64-S128-Fn32"
target triple = "arm64-apple-macosx"

declare void @llvm.memcpy.p0.p0.i64(ptr noalias writeonly captures(none), ptr noalias readonly captures(none), i64, i1 immarg)
  declare ptr @sink(ptr)

define void @loop(ptr %src, ptr %p2, ptr %p3) {
; CHECK-LABEL: @loop(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[T:%.*]] = alloca [40 x i8], align 8
; CHECK-NEXT:    br label [[BODY:%.*]]
; CHECK:       body:
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr [[T]], ptr [[SRC:%.*]], i64 16, i1 false)
; CHECK-NEXT:    [[T_PLUS_16:%.*]] = getelementptr i8, ptr [[T]], i64 16
; CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr [[T_PLUS_16]], ptr [[SRC]], i64 24, i1 false)
; CHECK-NEXT:    [[G1:%.*]] = getelementptr i8, ptr [[P3:%.*]], i64 40
; CHECK-NEXT:    store i8 0, ptr [[G1]], align 8
; CHECK-NEXT:    [[G2:%.*]] = getelementptr i8, ptr [[P2:%.*]], i64 48
; CHECK-NEXT:    [[V:%.*]] = load i8, ptr [[G2]], align 1
; CHECK-NEXT:    store i8 [[V]], ptr [[SRC]], align 1
; CHECK-NEXT:    [[TMP0:%.*]] = call ptr @sink(ptr [[T]])
; CHECK-NEXT:    br label [[BODY]]
;
entry:
  %t = alloca [40 x i8], align 8
  br label %body

body:
  ; GEPs below should not be hoisted as they fold with the memcpys.
  call void @llvm.memcpy.p0.p0.i64(ptr %t, ptr %src, i64 16, i1 false)
  %t_plus_16 = getelementptr i8, ptr %t, i64 16
  call void @llvm.memcpy.p0.p0.i64(ptr %t_plus_16, ptr %src, i64 24, i1 false)
  %g1 = getelementptr i8, ptr %p3, i64 40
  store i8 0, ptr %g1, align 8
  %g2 = getelementptr i8, ptr %p2, i64 48
  %v = load i8, ptr %g2, align 1
  store i8 %v, ptr %src, align 1
  call ptr @sink(ptr %t)
  br label %body
}
