; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -mtriple=aarch64-linux-gnu -mattr=+mops -passes=pre-isel-intrinsic-lowering -S -o - %s | FileCheck %s

declare void @llvm.memcpy.inline.p0.p0.i64(ptr nocapture writeonly, ptr nocapture readonly, i64, i1 immarg)

declare void @llvm.memset.inline.p0.i64(ptr nocapture writeonly, i8, i64, i1 immarg)

define void @memcpy_inline_n(ptr %dst, ptr %src, i64 %n) {
; CHECK-LABEL: @memcpy_inline_n(
; CHECK-NEXT:    call void @llvm.memcpy.inline.p0.p0.i64(ptr [[DST:%.*]], ptr [[SRC:%.*]], i64 [[N:%.*]], i1 false)
; CHECK-NEXT:    ret void
;
  call void @llvm.memcpy.inline.p0.p0.i64(ptr %dst, ptr %src, i64 %n, i1 false)
  ret void
}

define void @memset_inline_n(ptr %dst, i8 %v, i64 %n) {
; CHECK-LABEL: @memset_inline_n(
; CHECK-NEXT:    call void @llvm.memset.inline.p0.i64(ptr [[DST:%.*]], i8 [[V:%.*]], i64 [[N:%.*]], i1 false)
; CHECK-NEXT:    ret void
;
  call void @llvm.memset.inline.p0.i64(ptr %dst, i8 %v, i64 %n, i1 false)
  ret void
}
