; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64-linux-gnu -mattr=+mops -O2 < %s | FileCheck %s

declare void @llvm.memcpy.inline.p0.p0.i64(ptr nocapture writeonly, ptr nocapture readonly, i64, i1 immarg)

declare void @llvm.memset.inline.p0.i64(ptr nocapture writeonly, i8, i64, i1 immarg)

define void @memcpy_inline_n(ptr %dst, ptr %src, i64 %n) {
; CHECK-LABEL: memcpy_inline_n:
; CHECK:       // %bb.0:
; CHECK-NEXT:    cbz x2, .LBB0_3
; CHECK-NEXT:  // %bb.1: // %dynamic-memcpy-expansion-main-body.preheader
; CHECK-NEXT:    mov x8, xzr
; CHECK-NEXT:  .LBB0_2: // %dynamic-memcpy-expansion-main-body
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    ldrb w9, [x1, x8]
; CHECK-NEXT:    strb w9, [x0, x8]
; CHECK-NEXT:    add x8, x8, #1
; CHECK-NEXT:    cmp x8, x2
; CHECK-NEXT:    b.lo .LBB0_2
; CHECK-NEXT:  .LBB0_3: // %dynamic-memcpy-post-expansion
; CHECK-NEXT:    ret
  call void @llvm.memcpy.inline.p0.p0.i64(ptr %dst, ptr %src, i64 %n, i1 false)
  ret void
}

define void @memset_inline_n(ptr %dst, i8 %v, i64 %n) {
; CHECK-LABEL: memset_inline_n:
; CHECK:       // %bb.0:
; CHECK-NEXT:    cbz x2, .LBB1_3
; CHECK-NEXT:  // %bb.1: // %dynamic-memset-expansion-main-body.preheader
; CHECK-NEXT:    mov x8, xzr
; CHECK-NEXT:  .LBB1_2: // %dynamic-memset-expansion-main-body
; CHECK-NEXT:    // =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    strb w1, [x0, x8]
; CHECK-NEXT:    add x8, x8, #1
; CHECK-NEXT:    cmp x8, x2
; CHECK-NEXT:    b.lo .LBB1_2
; CHECK-NEXT:  .LBB1_3: // %dynamic-memset-post-expansion
; CHECK-NEXT:    ret
  call void @llvm.memset.inline.p0.i64(ptr %dst, i8 %v, i64 %n, i1 false)
  ret void
}
